name: CI/CD - Lint, Test & Deploy to EC2

on:
  push:
    branches:
      - master # Trigger only when pushing to master branch

jobs:
  build-and-test:
    name: Run Lint and Test (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Use your local version (22.17.0)

      - name: Install dependencies
        run: npm install

      - name: Create uploads folder
        run: mkdir -p uploads # ✅ Fix: create folder ignored by Git

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }} # ✅ Test DB in secrets
        run: npm test

  deploy:
    name: Deploy to EC2 (CD)
    runs-on: ubuntu-latest
    needs: build-and-test # ✅ Only run if CI passes

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/node-app || exit 1
            git pull origin master
            npm install
            pm2 restart backend
